### ISSUE TITLE
Three new graph robustness papers at NeurIPS

### ISSUE THREAD

**Issue by jan-schuchardt** [gitgiter/Graph-Adversarial-Learning#4]
Hi!

Thanks again for maintaining this valuable resource.

We have three new NeurIPS papers on (provably) robust learning on graphs
and wanted to ask if we could include them.

---

In this paper, we revisit the problem of proving robustness for graphs from a perspective of geometric machine learning.
Among other things, we show that proving robustness w.r.t. graph edit distance is actually not as hard as one might think.

(Provable) Adversarial Robustness for Group Equivariant Tasks: Graphs, Point Clouds, Molecules, and More
https://openreview.net/forum?id=mLe63bAYc7
Code will be made available here: https://www.cs.cit.tum.de/daml/equivariance-robustness/

---

In this paper, we propose a procedure to prove robustness to adversaries that only control a limited number of nodes and only a limited fraction of their features / edges.

Hierarchical Randomized Smoothing
https://openreview.net/forum?id=6IhNHKyuJO
Code will be made available here: https://www.cs.cit.tum.de/daml/hierarchical-smoothing

---

In this paper, we revisit adversarial training for graph neural networks.

Adversarial Training for Graph Neural Networks: Pitfalls, Solutions, and New Directions
https://openreview.net/forum?id=GPtroppvUM
Code will be made available here: https://www.cs.cit.tum.de/daml/adversarial-training/

---

Thanks again,
Jan

**Comment by EdisonLeeeee** [comment]
Amazing, thank you so much for your contributions! Just added via 7fe3e1a83b74dff6bf193469966959822e9c61ac
